# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsnabblink(self):
    # Test name: test_snabblink
    # Step # | name | target | value
    # 1 | open | https://www.sfbok.se/ | 
    self.driver.get("https://www.sfbok.se/")
    # 2 | setWindowSize | 795x816 | 
    self.driver.set_window_size(795, 816)
    # 3 | assertText | linkText=Nyheter | Nyheter
    assert self.driver.find_element(By.LINK_TEXT, "Nyheter").text == "Nyheter"
    # 4 | close |  | 
    self.driver.close()
  
  def test_testasserttext(self):
    # Test name: test_assert_text
    # Step # | name | target | value
    # 1 | open | https://www.sfbok.se/ | 
    self.driver.get("https://www.sfbok.se/")
    # 2 | setWindowSize | 797x816 | 
    self.driver.set_window_size(797, 816)
    # 3 | assertText | linkText=Tips & Topplistor | Tips & Topplistor
    assert self.driver.find_element(By.LINK_TEXT, "Tips & Topplistor").text == "Tips & Topplistor"
    # 4 | close |  | 
    self.driver.close()
  
